#!/usr/bin/env python3
"""
Generate seed SQL for global_standards.

Sources:
  world_avg  — StrengthLevel.com (48M+ lifts). Tier→percentile mapping:
               Beginner=50th, Novice=75th, Intermediate=90th, Advanced=95th, Elite=99th.
  competition — Peer-reviewed research: "Normative data for the squat, bench press and
               deadlift in powerlifting" (n=809,986 entries). DOI: 10.1016/j.jsams.2024.08.007.
               90th-percentile anchor used; other percentiles scaled proportionally.

Lift scale factors derived from the same datasets (bench/squat and deadlift/squat ratios
are sex-specific because female bench is proportionally weaker than male bench).

Run:  python3 scripts/generate_global_standards.py > scripts/seed_global_standards.sql
"""

WEIGHT_CLASSES = {
    "M": [59, 66, 74, 83, 93, 105, 120, 999],
    "F": [47, 52, 57, 63, 69, 76, 84, 999],
}

# For the open (999) class, use these reference bodyweights
OPEN_REF_KG = {"M": 120, "F": 84}

# Squat 1RM bodyweight multipliers per sex / track / percentile.
# world_avg: anchored to StrengthLevel beginner–elite tiers (48 M lifts).
# competition: anchored to research paper 90th-percentile values; other
#              percentiles scaled from that anchor.
SQUAT_MULTIPLIERS = {
    "M": {
        "competition": {99: 3.40, 95: 3.10, 90: 2.83, 75: 2.35, 50: 1.85, 0: 0.0},
        "world_avg": {99: 2.50, 95: 2.00, 90: 1.60, 75: 1.20, 50: 0.90, 0: 0.0},
    },
    "F": {
        "competition": {99: 2.75, 95: 2.50, 90: 2.26, 75: 1.90, 50: 1.55, 0: 0.0},
        "world_avg": {99: 2.00, 95: 1.55, 90: 1.10, 75: 0.75, 50: 0.50, 0: 0.0},
    },
}

# Multipliers relative to squat 1RM, derived per sex from the same datasets.
# Male bench/squat ≈ 0.72 (StrengthLevel); female ≈ 0.60 (lower upper-body ratio).
# Deadlift/squat ≈ 1.15 for both (consistent across datasets).
# Total = squat + bench + deadlift expressed as a squat multiplier.
LIFT_SCALE = {
    "M": {"squat": 1.00, "bench": 0.72, "deadlift": 1.15, "total": 2.87},
    "F": {"squat": 1.00, "bench": 0.60, "deadlift": 1.17, "total": 2.77},
}

PERCENTILES = [99, 95, 90, 75, 50, 0]


def generate():
    rows = []
    for sex, classes in WEIGHT_CLASSES.items():
        for wc in classes:
            ref_bw = OPEN_REF_KG[sex] if wc == 999 else wc
            for track, pct_map in SQUAT_MULTIPLIERS[sex].items():
                for lift, lift_scale in LIFT_SCALE[sex].items():
                    for pct in PERCENTILES:
                        squat_mult = pct_map[pct]
                        min_kg = (
                            round(ref_bw * squat_mult * lift_scale, 1)
                            if squat_mult > 0
                            else 0.0
                        )
                        rows.append((lift, sex, wc, pct, min_kg, track))
    return rows


def main():
    rows = generate()
    print("-- Auto-generated by scripts/generate_global_standards.py")
    print(
        "-- Sources: StrengthLevel.com (world_avg) | DOI:10.1016/j.jsams.2024.08.007 (competition)"
    )
    print("-- Do not edit by hand; re-run the script to regenerate.\n")
    print("INSERT INTO global_standards")
    print("  (lift, sex, weight_class_kg, percentile, min_kg, track)")
    print("VALUES")
    formatted = [
        f"  ('{lift}', '{sex}', {wc}, {pct}, {min_kg}, '{track}')"
        for lift, sex, wc, pct, min_kg, track in rows
    ]
    print(",\n".join(formatted) + "\nON CONFLICT DO NOTHING;")


if __name__ == "__main__":
    main()
