#!/usr/bin/env python3
"""
Generate seed SQL for global_standards.

Percentile thresholds are derived from bodyweight multipliers:
  - competition: based on competitive powerlifting standards (IPF-style raw)
  - world_avg:   based on general gym-goer population

Run:  python scripts/generate_global_standards.py > scripts/seed_global_standards.sql
"""

WEIGHT_CLASSES = {
    'M': [59, 66, 74, 83, 93, 105, 120, 999],
    'F': [47, 52, 57, 63, 69, 76, 84, 999],
}

# For the open (999) class use these reference bodyweights
OPEN_REF_KG = {'M': 120, 'F': 84}

# Squat bodyweight multipliers per sex / track / percentile
SQUAT_MULTIPLIERS = {
    'M': {
        'competition': {99: 2.75, 95: 2.45, 90: 2.15, 75: 1.85, 50: 1.55, 0: 0.0},
        'world_avg':   {99: 1.75, 95: 1.50, 90: 1.30, 75: 1.10, 50: 0.85, 0: 0.0},
    },
    'F': {
        'competition': {99: 2.00, 95: 1.75, 90: 1.55, 75: 1.30, 50: 1.05, 0: 0.0},
        'world_avg':   {99: 1.10, 95: 0.90, 90: 0.80, 75: 0.65, 50: 0.50, 0: 0.0},
    },
}

# Multiplier relative to squat 1RM
LIFT_SCALE = {
    'squat':    1.00,
    'bench':    0.65,
    'deadlift': 1.20,
    'total':    2.75,
}

PERCENTILES = [99, 95, 90, 75, 50, 0]


def generate():
    rows = []
    for sex, classes in WEIGHT_CLASSES.items():
        for wc in classes:
            ref_bw = OPEN_REF_KG[sex] if wc == 999 else wc
            for track, pct_map in SQUAT_MULTIPLIERS[sex].items():
                for lift, lift_scale in LIFT_SCALE.items():
                    for pct in PERCENTILES:
                        squat_mult = pct_map[pct]
                        min_kg = round(ref_bw * squat_mult * lift_scale, 1) if squat_mult > 0 else 0.0
                        rows.append((lift, sex, wc, pct, min_kg, track))
    return rows


def main():
    rows = generate()
    print("-- Auto-generated by scripts/generate_global_standards.py")
    print("-- Do not edit by hand; re-run the script to regenerate.\n")
    print("INSERT INTO global_standards")
    print("  (lift, sex, weight_class_kg, percentile, min_kg, track)")
    print("VALUES")
    formatted = [
        f"  ('{lift}', '{sex}', {wc}, {pct}, {min_kg}, '{track}')"
        for lift, sex, wc, pct, min_kg, track in rows
    ]
    print(",\n".join(formatted) + "\nON CONFLICT DO NOTHING;")


if __name__ == '__main__':
    main()
