apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-initdb
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  01-schema.sql: |
{{ .Files.Get "files/initdb/01-schema.sql" | indent 4 }}
  02-seed-global-standards.sql: |
{{ .Files.Get "files/initdb/02-seed-global-standards.sql" | indent 4 }}
