apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-auth.fullname" . }}-initdb
  labels:
    {{- include "postgres-auth.labels" . | nindent 4 }}
data:
  01-schema.sql: |
{{ .Files.Get "files/initdb/01-schema.sql" | indent 4 }}
