apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/sagivperetz04-hue/myfitnessrank.git
    targetRevision: feature/RND-001-add-claude-project-config
    path: helm/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: myfitnessrank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
