apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/sagivperetz04-hue/myfitnessrank.git
    targetRevision: master
    path: helm/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: myfitnessrank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
