apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/sagivperetz04-hue/myfitnessrank.git
    targetRevision: feature/RND-002-auth-service
    path: helm/postgres-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: myfitnessrank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
